customization:
  distribution_code_name: Weasel
  distribution_version: 0.17.4
  generator: "Rime::SwitcherSettings"
  modified_time: "Mon Apr 13 15:09:10 2026"
  rime_version: 1.13.1
patch:
  schema_list:
    - {schema: luna_pinyin_simp}
  menu/page_size: 7
  ascii_composer/good_old_caps_lock: false
  ascii_composer/switch_key:
    Caps_Lock: commit_code
    Shift_L: noop
    Shift_R: noop
